# Generated by Django 4.2.1 on 2023-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('number', models.IntegerField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
